### ISSUE TITLE
Proposer should not be able to vote for new proposal.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividend.frontend#1]
Dividend frontend v140 Env QA4 
Created new proposal for deliadally. Was able to vote using freeosfreeos even though he was set up as the proposer in whitelist. Voting was successful. In the Whitelist, freeosfreeos, the proposer has a vote of 2 (accept) against it. Expects the proposer freeosfreeos not to b

![FreeOS App 7-19-2021 12-54-55 PM](https://user-images.githubusercontent.com/77765830/126099437-63dcb0b5-b6c3-4d86-9178-c10a14b75da4.png)

![Account - Proton Testnet Bloks-io 7-19-2021 12-58-27 PM](https://user-images.githubusercontent.com/77765830/126099387-81fdbdf3-1731-463e-a57e-a0f1591a7c8f.png)

**Comment by andyzal** [comment]
Actually, the frontend recognize proposer login. The proposer cannot vote, the 'Submit Vote' button is inactive for proposer and  displays tooltip with explanation.
