### ISSUE TITLE
UI Observation: Home Page 

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividend.frontend#14]
17/11/21 Test Dividend New UX Frontend. Env:QA5 Link: https://mrmat-oqaaa-aaaad-qal4q-cai.raw.ic0.app/#/
Login as vivvestin -> Connect Wallet -> also showing FreeDAO logo. Expecting the new OnChain Logo.

![Dividend App 17-11-2021 14-37-19](https://user-images.githubusercontent.com/77765830/142093681-4594d516-c4e3-4193-8019-f288d6c09e5a.png)

**Comment by andyzal** [comment]
Can Change. (So far I had forbidden to change anything :) )

**Comment by judytan21** [comment]
6/12/21 This issue is no longer relevant. Closing issue.
