### ISSUE TITLE
UI Obsevation: Hamburger menu

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividend.frontend#15]
17/11/21 Test Dividend New UX Frontend. Env:QA5 Link: https://mrmat-oqaaa-aaaad-qal4q-cai.raw.ic0.app/#/
On selecting the hamburger menu, suggest using the Vote icon in Dave's UX simply because it depicts voting.

![Dividend App 17-11-2021 14-59-44](https://user-images.githubusercontent.com/77765830/142095522-356fe2d6-9c1a-493b-9422-39b96fb72a60.png)

Dave's Vote icon 

![image](https://user-images.githubusercontent.com/77765830/142095766-8507c1bf-feff-4bc0-90eb-53086fb42154.png)

**Comment by andyzal** [comment]
Only Home icon do not much as it was not in set which I received from Dave. The other icons may be scaled slightly different as it was not trivial to join them to icons library, I displayed them as a pictures.

**Comment by judytan21** [comment]
6/12/21 Closing issue as due to time constraints, this is now part of Issue#23 Nice-to-haves.
