### ISSUE TITLE
UI Change: Analytics Page

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividend.frontend#26]
6/12/21 UI change request following discussion with JeromeK on 1/12/21. Ver# v0.9.3 Env:QA5 Link: https://freeos.online/#/
On Analytics page, please make the following changes:
1. Rename "Data Update" to "Update Data".
2. Rename "DAO" to "FreeDAO".

![Dividend App 06-12-2021 13-14-46](https://user-images.githubusercontent.com/77765830/144770057-4a98a469-cf16-48e5-a823-9a32128e0bbd.png)

**Comment by andyzal** [comment]
Done. DAO Changed to FreeDAO on all PVA (Proposal, Vote, Analytics) pages.
