### ISSUE TITLE
Proposal has expired but frontend still showing there's an active proposal.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividend.frontend#3]
v140. QA4
On the frontend, label beside the info icon was showing as Proposal Active when: 
1. Proposal has already expired after an hour
2. Proposal acct was reset to acct(empty) due to a voter rejecting the proposal.
Expecting the label to show "No active proposal' in both scenarios.
21/7/21-discussed with JeromeK/Andrew/Tom and decision was to log issue for Andrew to fix
![FreeOS App 7-22-2021 12-31-19 PM](https://user-images.githubusercontent.com/77765830/126576390-4d5afce2-5196-4745-9785-c207d2b8c8ec.png)

**Comment by andyzal** [comment]
The "Active Proposal" indicator located on both "Proposal" and "Vote" pages should work well. Additionally, when proposal is active the countdown timer is displayed. Note: The timer displays minutes and 1/100th of a minute (not seconds). For example 13.97  13 minutes and 97/100 of a minute. Anyway, no one will vote at the last minute :)

**Comment by judytan21** [comment]
1/9/21 Retest. Scenario 1. Created a new proposal for freeandyandy. Then both voters billbeaumont n freedaodao voted to reject proposal. In the backend, proposal in freeosdiv5 was set to empty.
1	empty	0	0.00000000000000000	1	1630453939	0.0000 POINT	0	0.0000 POINT
Frontend shows there is no active proposal. Correct. Fixed.
![Dividend App 01-09-2021 11-53-35](https://user-images.githubusercontent.com/77765830/13159
0762-d75bcfbf-d202-4359-b331-5e355b8fdc1d.png)

Scenario 2: Create a new wayfarer proposal for freeandyandy.
1	freeandyandy	2	2.00000000000000000	0	1630458554	200.0000 POINT	0	0.0000 POINT
Checked after an hour when the proposal has expired. Frontend now showing there is no active proposal. Correct. Fixed.
