### ISSUE TITLE
On NFT change ownership pop up, enable 'Make Change' button only when the required info has been entered.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividend.frontend#8]
v140 QA4 
On the 'Change NFT Ownership' pop up, enable the 'Make Change' button only when the required info has been entered. The button should be disabled until the required info has been filled. Currently, if no details were entered, the pop up 'Loading   Preparing request' is displayed. 
22/7/21 Discord QA - discussed with JeromeK and he has requested Andrew to make the change.
![FreeOS App 7-22-2021 12-31-19 PM](https://user-images.githubusercontent.com/77765830/126579864-988fdae2-e789-4289-b8f9-deb25ea57f96.png)

**Comment by andyzal** [comment]
Corrected.
